In [1]:
# Imports
import requests
from bs4 import BeautifulSoup as bs

In [3]:
# request the website
r = requests.get('https://ncov2019.live/data')

# get the html from the request
page = r.text

# create a beautiful soup object and use lxml to proccess the html
soup = bs(page, 'lxml')

In [4]:
# get the body html
soup.find('body')

<body class="data">
<nav class="navbar fixed-top navbar-expand-lg navbar-dark">
<a class="navbar-brand" href="/data">
<span style="padding-bottom: 4px;">
<svg aria-hidden="true" class="svg-inline--fa fa-globe fa-w-16" data-icon="globe" data-prefix="fas" focusable="false" role="img" style="width: 25px;" viewbox="0 0 496 512" xmlns="http://www.w3.org/2000/svg">
<path d="M336.5 160C322 70.7 287.8 8 248 8s-74 62.7-88.5 152h177zM152 256c0 22.2 1.2 43.5 3.3 64h185.3c2.1-20.5 3.3-41.8 3.3-64s-1.2-43.5-3.3-64H155.3c-2.1 20.5-3.3 41.8-3.3 64zm324.7-96c-28.6-67.9-86.5-120.4-158-141.6 24.4 33.8 41.2 84.7 50 141.6h108zM177.2 18.4C105.8 39.6 47.8 92.1 19.3 160h108c8.7-56.9 25.5-107.8 49.9-141.6zM487.4 192H372.7c2.1 21 3.3 42.5 3.3 64s-1.2 43-3.3 64h114.6c5.5-20.5 8.6-41.8 8.6-64s-3.1-43.5-8.5-64zM120 256c0-21.5 1.2-43 3.3-64H8.6C3.2 212.5 0 233.8 0 256s3.2 43.5 8.6 64h114.6c-2-21-3.2-42.5-3.2-64zm39.5 96c14.5 89.3 48.7 152 88.5 152s74-62.7 88.5-152h-177zm159.3 141.6c71.4-21.2 129.4-73.7 158-141.6h-108c-8.8 56.9-25.6 107.8-50 141.6zM19.3 352c28.6 67.9 86.5 120.4 158 141.6-24.4-33.8-41.2-84.7-50-141.6h-108z" fill="currentColor"></path>
</svg>
</span>
    nCoV2019.live
  </a>
<div class="navbar-nav ml-auto mr-2 mobile-kofi">
<script src="https://ko-fi.com/widgets/widget_2.js" type="text/javascript"></script>
<script type="text/javascript">
        kofiwidget2.init('Buy Me a Coffee', '#e02828', 'E1E71GQ8N');
        kofiwidget2.draw();
      </script>
</div>
<button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<a class="nav-link" href="/data" style="color: white; font-size: 20px; font-weight: bolder;">Data <span class="sr-only">(current)</span></a>
</li>
<li class="nav-item">
<a class="nav-link" href="/map" style="color: white; font-size: 20px; font-weight: bolder;">Map</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/wiki" style="color: white; font-size: 20px; font-weight: bolder;">Wiki</a>
</li>
<!--
      <li class="nav-item">
        <a style="color: white; font-size: 20px; font-weight: bolder;" class="nav-link" href="/email">Newsletter</a>
      </li> -->
<li class="nav-item">
<a class="nav-link" href="/about" style="color: white; font-size: 20px; font-weight: bolder;">About</a>
</li>
<li class="nav-item">
<a class="nav-link" href="/calculator" style="color: white; font-size: 20px; font-weight: bolder;">Survival Rate Calculator</a>
</li>
</ul>
<ul class="navbar-nav ml-auto">
<li class="flex">
<div class="social-btns d-flex flex-wrap">
<div class="col my-auto p-0 mr-2">
<a href="https://www.instagram.com/avischiffmann/" target="_blank"><button class="btn btn-primary btn-instagram rounded" style="font-size: 14px;background: radial-gradient(circle at 0% 107%, #fd5949 45%,#d6249f 70%) !important;height: 30px;padding: 0 12px;white-space: nowrap;" type=""><i class="fab fa-instagram"></i> Follow @AviSchiffmann</button></a>
</div>
<div class="pos-rel" style="top: 6px;margin-right: 10px;">
<a class="twitter-follow-button" data-show-count="false" data-size="large" href="https://twitter.com/AviSchiffmann?ref_src=twsrc%5Etfw">Follow @AviSchiffmann</a><script async="" charset="utf-8" src="https://platform.twitter.com/widgets.js"></script>
</div>
</div>
<script src="https://ko-fi.com/widgets/widget_2.js" type="text/javascript"></script>
<script type="text/javascript">
          kofiwidget2.init('Buy Me a Coffee', '#e02828', 'E1E71GQ8N');
          kofiwidget2.draw();
        </script>
</li>
</ul>
</div>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark d-block d-sm-none" style="position: relative;top: 60px;">
<div class="navbar-nav mr-auto" style="width: 100%;">
<div class="dropdown" style="width: 100%;">
<button aria-expanded="false" aria-haspopup="true" class="btn dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton" style="width: 100%; text-align: left;" type="button">
          Jump to Region
        </button>
<div aria-labelledby="dropdownMenuButton" class="dropdown-menu dropdown-menu-right">
<a class="dropdown-item" href="#QuickFacts">Quick Facts</a>
<a class="dropdown-item" href="#world">World</a>
<a class="dropdown-item" href="#unitedstates">USA</a>
<a class="dropdown-item" href="#canada">Canada</a>
<a class="dropdown-item" href="#australia">Australia</a>
<a class="dropdown-item" href="#europe">Europe</a>
<a class="dropdown-item" href="#asia">Asia</a>
<a class="dropdown-item" href="#africa">Africa</a>
<a class="dropdown-item" href="#oceania">Oceania</a>
<a class="dropdown-item" href="#southamerica">South America</a>
<a class="dropdown-item" href="#northamerica">North America</a>
<a class="dropdown-item" href="#ships">Ships</a>
<a class="dropdown-item" href="#italy">Italy</a>
<a class="dropdown-item" href="#russia">Russia</a>
<a class="dropdown-item" href="#ireland">Ireland</a>
</div>
</div>
<div class="mobile-nav-legend sort-copy">
<div class="mobile-nav-legend-label">
<span class="legend-label">Sort by:   </span>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_saved">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="saved">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="saved">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="saved">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="saved">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_world">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="world">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="world">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="world">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="world">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_world">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="14168735">
<span class="legend-label confirmed">14,168,735</span>
</div>
<div class="mobile-nav-legend-item" data-order="598274">
<span class="legend-label deceased">598,274</span>
</div>
<div class="mobile-nav-legend-item" data-order="8210408">
<span class="legend-label recovered">8,210,408</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_unitedstates">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="unitedstates">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="unitedstates">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="unitedstates">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="unitedstates">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_unitedstates">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="3762881">
<span class="legend-label confirmed">3,762,881</span>
</div>
<div class="mobile-nav-legend-item" data-order="141923">
<span class="legend-label deceased">141,923</span>
</div>
<div class="mobile-nav-legend-item" data-order="1710222">
<span class="legend-label recovered">1,710,222</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_canada">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="canada">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="canada">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="canada">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="canada">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_canada">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="111131">
<span class="legend-label confirmed">111,131</span>
</div>
<div class="mobile-nav-legend-item" data-order="8874">
<span class="legend-label deceased">8,874</span>
</div>
<div class="mobile-nav-legend-item" data-order="96674">
<span class="legend-label recovered">96,674</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_australia">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="australia">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="australia">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="australia">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="australia">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_australia">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="11235">
<span class="legend-label confirmed">11,235</span>
</div>
<div class="mobile-nav-legend-item" data-order="116">
<span class="legend-label deceased">116</span>
</div>
<div class="mobile-nav-legend-item" data-order="8117">
<span class="legend-label recovered">8,117</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_europe">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="europe">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="europe">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="europe">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="europe">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_europe">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="2969932">
<span class="legend-label confirmed">2,969,932</span>
</div>
<div class="mobile-nav-legend-item" data-order="205372">
<span class="legend-label deceased">205,372</span>
</div>
<div class="mobile-nav-legend-item" data-order="1796800">
<span class="legend-label recovered">1,796,800</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_asia">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="asia">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="asia">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="asia">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="asia">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_asia">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="4015023">
<span class="legend-label confirmed">4,015,023</span>
</div>
<div class="mobile-nav-legend-item" data-order="88631">
<span class="legend-label deceased">88,631</span>
</div>
<div class="mobile-nav-legend-item" data-order="2835615">
<span class="legend-label recovered">2,835,615</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_africa">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="africa">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="africa">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="africa">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="africa">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_africa">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="683492">
<span class="legend-label confirmed">683,492</span>
</div>
<div class="mobile-nav-legend-item" data-order="14673">
<span class="legend-label deceased">14,673</span>
</div>
<div class="mobile-nav-legend-item" data-order="360379">
<span class="legend-label recovered">360,379</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_oceania">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="oceania">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="oceania">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="oceania">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="oceania">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_oceania">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="12824">
<span class="legend-label confirmed">12,824</span>
</div>
<div class="mobile-nav-legend-item" data-order="137">
<span class="legend-label deceased">137</span>
</div>
<div class="mobile-nav-legend-item" data-order="9648">
<span class="legend-label recovered">9,648</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_southamerica">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="southamerica">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="southamerica">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="southamerica">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="recovered" data-region="southamerica">
<span class="legend-marker recovered">•</span>
<span class="legend-label">Recovered</span>
</div>
</div>
</div>
<div class="mobile-nav-legend totals" id="mobile-nav-total_southamerica">
<div class="mobile-nav-legend-label name">
<span class="legend-label">TOTAL</span>
</div>
<div class="mobile-nav-legend-items">
<div class="mobile-nav-legend-item" data-order="3163015">
<span class="legend-label confirmed">3,163,015</span>
</div>
<div class="mobile-nav-legend-item" data-order="114898">
<span class="legend-label deceased">114,898</span>
</div>
<div class="mobile-nav-legend-item" data-order="2082760">
<span class="legend-label recovered">2,082,760</span>
</div>
</div>
</div>
<div class="mobile-nav-legend" id="mobile-nav-legend_northamerica">
<div class="category_sort mobile-nav-legend-item" data-action="name" data-region="northamerica">
<span class="legend-marker name">•</span>
<span class="legend-label">Name</span>
</div>
<div class="mobile-nav-legend-items">
<div class="category_sort mobile-nav-legend-item" data-action="confirmed" data-region="northamerica">
<span class="legend-marker confirmed">•</span>
<span class="legend-label sorted-column--desc">Confirmed</span>
</div>
<div class="category_sort mobile-nav-legend-item" data-action="deaths" data-region="northamerica">
<span class="legend-marker deceased">•</span>
<span class="legend-label">Deaths</span>
</div>

In [5]:
# get world data table
table = soup.find('table', attrs={'id':'sortable_table_world'})
table

<table class="display responsive" id="sortable_table_world" style="opacity:0">
<thead>
<tr>
<th class="text--gray">Name</th>
<th class="text--gray">Confirmed</th>
<th class="text--gray">Changes Today</th>
<th class="text--gray">Percentage Day Change</th>
<th class="text--gray">Critical</th>
<th class="text--gray">Deceased</th>
<th class="text--gray">Changes Today</th>
<th class="text--gray">Percentage Death Change</th>
<th class="text--gray">Tests</th>
<th class="text--gray">Active</th>
<th class="text--gray">Recovered</th>
</tr>
</thead>
<tbody>
<tr>
<td class="text--gray">
          TOTAL
        </td>
<td class="text--green" data-order="14168735">
          14,168,735
        </td>
<td class="text--green" data-order="229387">
          229,387
        </td>
<td class="text--green" data-order="1.65">
          1.65%
        </td>
<td class="text--orange" data-order="59936">
          59,936
        </td>
<td class="text--red" data-order="598274">
          598,274
        </td>
<td class="text--red" data-order="5292">
          5,292
        </td>
<td class="text--red" data-order="0.89">
          0.89%
        </td>
<td class="text--amber" data-order="287716113">
          287,716,113
        </td>
<td class="text--yellow" data-order="5192356">
          5,192,356
        </td>
<td class="text--blue" data-order="8210408">
          8,210,408
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Hong Kong" data-status="unselected" data-type="country">★</span>


            Hong Kong

        </td>
<td class="text--green" data-order="1714">
          1,714
        </td>
<td class="text--green" data-order="58">
          58
        </td>
<td class="text--green" data-order="3.5">
          3.5%
        </td>
<td class="text--orange" data-order="8">
          8
        </td>
<td class="text--red" data-order="11">
          11
        </td>
<td class="text--red" data-order="1">
          1
        </td>
<td class="text--red" data-order="10">
          10%
        </td>
<td class="text--amber" data-order="442256">
          442,256
        </td>
<td class="text--yellow" data-order="439">
          439
        </td>
<td class="text--blue" data-order="1264">
          1,264
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Macao" data-status="unselected" data-type="country">★</span>


            Macao

        </td>
<td class="text--green" data-order="46">
          46
        </td>
<td class="text--green" data-order="0">
          0
        </td>
<td class="text--green" data-order="0">
          0%
        </td>
<td class="text--orange" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="4071">
          4,071
        </td>
<td class="text--yellow" data-order="-1">
          Unknown
        </td>
<td class="text--blue" data-order="45">
          45
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Afghanistan" data-status="unselected" data-type="country">★</span>


            Afghanistan

        </td>
<td class="text--green" data-order="35229">
          35,229
        </td>
<td class="text--green" data-order="159">
          159
        </td>
<td class="text--green" data-order="0.45">
          0.45%
        </td>
<td class="text--orange" data-order="31">
          31
        </td>
<td class="text--red" data-order="1147">
          1,147
        </td>
<td class="text--red" data-order="34">
          34
        </td>
<td class="text--red" data-order="3.05">
          3.05%
        </td>
<td class="text--amber" data-order="82924">
          82,924
        </td>
<td class="text--yellow" data-order="10931">
          10,931
        </td>
<td class="text--blue" data-order="23151">
          23,151
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Albania" data-status="unselected" data-type="country">★</span>


            Albania

        </td>
<td class="text--green" data-order="3906">
          3,906
        </td>
<td class="text--green" data-order="55">
          55
        </td>
<td class="text--green" data-order="1.43">
          1.43%
        </td>
<td class="text--orange" data-order="9">
          9
        </td>
<td class="text--red" data-order="107">
          107
        </td>
<td class="text--red" data-order="3">
          3
        </td>
<td class="text--red" data-order="2.88">
          2.88%
        </td>
<td class="text--amber" data-order="30551">
          30,551
        </td>
<td class="text--yellow" data-order="1585">
          1,585
        </td>
<td class="text--blue" data-order="2214">
          2,214
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Algeria" data-status="unselected" data-type="country">★</span>


            Algeria

        </td>
<td class="text--green" data-order="21948">
          21,948
        </td>
<td class="text--green" data-order="593">
          593
        </td>
<td class="text--green" data-order="2.78">
          2.78%
        </td>
<td class="text--orange" data-order="61">
          61
        </td>
<td class="text--red" data-order="1057">
          1,057
        </td>
<td class="text--red" data-order="5">
          5
        </td>
<td class="text--red" data-order="0.48">
          0.48%
        </td>
<td class="text--amber" data-order="-1">
          Unknown
        </td>
<td class="text--yellow" data-order="-1">
          Unknown
        </td>
<td class="text--blue" data-order="15430">
          15,430
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Andorra" data-status="unselected" data-type="country">★</span>


            Andorra

        </td>
<td class="text--green" data-order="880">
          880
        </td>
<td class="text--green" data-order="3">
          3
        </td>
<td class="text--green" data-order="0.34">
          0.34%
        </td>
<td class="text--orange" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="52">
          52
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="3750">
          3,750
        </td>
<td class="text--yellow" data-order="25">
          25
        </td>
<td class="text--blue" data-order="803">
          803
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Angola" data-status="unselected" data-type="country">★</span>


            Angola

        </td>
<td class="text--green" data-order="638">
          638
        </td>
<td class="text--green" data-order="31">
          31
        </td>
<td class="text--green" data-order="5.11">
          5.11%
        </td>
<td class="text--orange" data-order="6">
          6
        </td>
<td class="text--red" data-order="29">
          29
        </td>
<td class="text--red" data-order="1">
          1
        </td>
<td class="text--red" data-order="3.57">
          3.57%
        </td>
<td class="text--amber" data-order="10000">
          10,000
        </td>
<td class="text--yellow" data-order="410">
          410
        </td>
<td class="text--blue" data-order="199">
          199
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Antigua and Barbuda" data-status="unselected" data-type="country">★</span>


            Antigua and Barbuda

        </td>
<td class="text--green" data-order="74">
          74
        </td>
<td class="text--green" data-order="0">
          0
        </td>
<td class="text--green" data-order="0">
          0%
        </td>
<td class="text--orange" data-order="1">
          1
        </td>
<td class="text--red" data-order="3">
          3
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="901">
          901
        </td>
<td class="text--yellow" data-order="14">
          14
        </td>
<td class="text--blue" data-order="57">
          57
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Argentina" data-status="unselected" data-type="country">★</span>


            Argentina

        </td>
<td class="text--green" data-order="119301">
          119,301
        </td>
<td class="text--green" data-order="4518">
          4,518
        </td>
<td class="text--green" data-order="3.94">
          3.94%
        </td>
<td class="text--orange" data-order="752">
          752
        </td>
<td class="text--red" data-order="2178">
          2,178
        </td>
<td class="text--red" data-order="66">
          66
        </td>
<td class="text--red" data-order="3.13">
          3.13%
        </td>
<td class="text--amber" data-order="519281">
          519,281
        </td>
<td class="text--yellow" data-order="67343">
          67,343
        </td>
<td class="text--blue" data-order="49780">
          49,780
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Armenia" data-status="unselected" data-type="country">★</span>


            Armenia

        </td>
<td class="text--green" data-order="34001">
          34,001
        </td>
<td class="text--green" data-order="442">
          442
        </td>
<td class="text--green" data-order="1.32">
          1.32%
        </td>
<td class="text--orange" data-order="10">
          10
        </td>
<td class="text--red" data-order="620">
          620
        </td>
<td class="text--red" data-order="13">
          13
        </td>
<td class="text--red" data-order="2.14">
          2.14%
        </td>
<td class="text--amber" data-order="143114">
          143,114
        </td>
<td class="text--yellow" data-order="10889">
          10,889
        </td>
<td class="text--blue" data-order="22492">
          22,492
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Austria" data-status="unselected" data-type="country">★</span>


            Austria

        </td>
<td class="text--green" data-order="19439">
          19,439
        </td>
<td class="text--green" data-order="169">
          169
        </td>
<td class="text--green" data-order="0.88">
          0.88%
        </td>
<td class="text--orange" data-order="11">
          11
        </td>
<td class="text--red" data-order="711">
          711
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="734413">
          734,413
        </td>
<td class="text--yellow" data-order="1393">
          1,393
        </td>
<td class="text--blue" data-order="17335">
          17,335
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Azerbaijan" data-status="unselected" data-type="country">★</span>


            Azerbaijan

        </td>
<td class="text--green" data-order="26636">
          26,636
        </td>
<td class="text--green" data-order="471">
          471
        </td>
<td class="text--green" data-order="1.8">
          1.8%
        </td>
<td class="text--orange" data-order="66">
          66
        </td>
<td class="text--red" data-order="341">
          341
        </td>
<td class="text--red" data-order="7">
          7
        </td>
<td class="text--red" data-order="2.1">
          2.1%
        </td>
<td class="text--amber" data-order="601500">
          601,500
        </td>
<td class="text--yellow" data-order="8490">
          8,490
        </td>
<td class="text--blue" data-order="17805">
          17,805
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="The Bahamas" data-status="unselected" data-type="country">★</span>


            The Bahamas

        </td>
<td class="text--green" data-order="129">
          129
        </td>
<td class="text--green" data-order="5">
          5
        </td>
<td class="text--green" data-order="4.03">
          4.03%
        </td>
<td class="text--orange" data-order="1">
          1
        </td>
<td class="text--red" data-order="11">
          11
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="2570">
          2,570
        </td>
<td class="text--yellow" data-order="27">
          27
        </td>
<td class="text--blue" data-order="91">
          91
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Bahrain" data-status="unselected" data-type="country">★</span>


            Bahrain

        </td>
<td class="text--green" data-order="35473">
          35,473
        </td>
<td class="text--green" data-order="389">
          389
        </td>
<td class="text--green" data-order="1.11">
          1.11%
        </td>
<td class="text--orange" data-order="47">
          47
        </td>
<td class="text--red" data-order="124">
          124
        </td>
<td class="text--red" data-order="3">
          3
        </td>
<td class="text--red" data-order="2.48">
          2.48%
        </td>
<td class="text--amber" data-order="710686">
          710,686
        </td>
<td class="text--yellow" data-order="4161">
          4,161
        </td>
<td class="text--blue" data-order="31188">
          31,188
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Bangladesh" data-status="unselected" data-type="country">★</span>


            Bangladesh

        </td>
<td class="text--green" data-order="199357">
          199,357
        </td>
<td class="text--green" data-order="3034">
          3,034
        </td>
<td class="text--green" data-order="1.55">
          1.55%
        </td>
<td class="text--orange" data-order="1">
          1
        </td>
<td class="text--red" data-order="2547">
          2,547
        </td>
<td class="text--red" data-order="51">
          51
        </td>
<td class="text--red" data-order="2.04">
          2.04%
        </td>
<td class="text--amber" data-order="1006751">
          1,006,751
        </td>
<td class="text--yellow" data-order="88085">
          88,085
        </td>
<td class="text--blue" data-order="108725">
          108,725
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Barbados" data-status="unselected" data-type="country">★</span>


            Barbados

        </td>
<td class="text--green" data-order="104">
          104
        </td>
<td class="text--green" data-order="0">
          0
        </td>
<td class="text--green" data-order="0">
          0%
        </td>
<td class="text--orange" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="7">
          7
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="9270">
          9,270
        </td>
<td class="text--yellow" data-order="6">
          6
        </td>
<td class="text--blue" data-order="91">
          91
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Belarus" data-status="unselected" data-type="country">★</span>


            Belarus

        </td>
<td class="text--green" data-order="65782">
          65,782
        </td>
<td class="text--green" data-order="159">
          159
        </td>
<td class="text--green" data-order="0.24">
          0.24%
        </td>
<td class="text--orange" data-order="89">
          89
        </td>
<td class="text--red" data-order="491">
          491
        </td>
<td class="text--red" data-order="6">
          6
        </td>
<td class="text--red" data-order="1.24">
          1.24%
        </td>
<td class="text--amber" data-order="1162280">
          1,162,280
        </td>
<td class="text--yellow" data-order="7921">
          7,921
        </td>
<td class="text--blue" data-order="57370">
          57,370
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Belgium" data-status="unselected" data-type="country">★</span>


            Belgium

        </td>
<td class="text--green" data-order="63238">
          63,238
        </td>
<td class="text--green" data-order="199">
          199
        </td>
<td class="text--green" data-order="0.32">
          0.32%
        </td>
<td class="text--orange" data-order="28">
          28
        </td>
<td class="text--red" data-order="9795">
          9,795
        </td>
<td class="text--red" data-order="3">
          3
        </td>
<td class="text--red" data-order="0.03">
          0.03%
        </td>
<td class="text--amber" data-order="1429053">
          1,429,053
        </td>
<td class="text--yellow" data-order="36174">
          36,174
        </td>
<td class="text--blue" data-order="17269">
          17,269
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Belize" data-status="unselected" data-type="country">★</span>


            Belize

        </td>
<td class="text--green" data-order="40">
          40
        </td>
<td class="text--green" data-order="0">
          0
        </td>
<td class="text--green" data-order="0">
          0%
        </td>
<td class="text--orange" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="2">
          2
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="2786">
          2,786
        </td>
<td class="text--yellow" data-order="16">
          16
        </td>
<td class="text--blue" data-order="22">
          22
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Benin" data-status="unselected" data-type="country">★</span>


            Benin

        </td>
<td class="text--green" data-order="1602">
          1,602
        </td>
<td class="text--green" data-order="139">
          139
        </td>
<td class="text--green" data-order="9.5">
          9.5%
        </td>
<td class="text--orange" data-order="1">
          1
        </td>
<td class="text--red" data-order="31">
          31
        </td>
<td class="text--red" data-order="3">
          3
        </td>
<td class="text--red" data-order="10.71">
          10.71%
        </td>
<td class="text--amber" data-order="72832">
          72,832
        </td>
<td class="text--yellow" data-order="789">
          789
        </td>
<td class="text--blue" data-order="782">
          782
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Bhutan" data-status="unselected" data-type="country">★</span>


            Bhutan

        </td>
<td class="text--green" data-order="86">
          86
        </td>
<td class="text--green" data-order="2">
          2
        </td>
<td class="text--green" data-order="2.38">
          2.38%
        </td>
<td class="text--orange" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="-1">
          Unknown
        </td>
<td class="text--red" data-order="0">
          0
        </td>
<td class="text--red" data-order="0">
          0%
        </td>
<td class="text--amber" data-order="39633">
          39,633
        </td>
<td class="text--yellow" data-order="-1">
          Unknown
        </td>
<td class="text--blue" data-order="78">
          78
        </td>
</tr>
<tr>
<td class="text--gray">
<span class="save-button" data-name="Bolivia" data-status="unselected" data-type="country">★</span>


            Bolivia

        </td>

In [6]:
# get table rows
tableRows = table.findAll('tr')
tableRows

[<tr>
 <th class="text--gray">Name</th>
 <th class="text--gray">Confirmed</th>
 <th class="text--gray">Changes Today</th>
 <th class="text--gray">Percentage Day Change</th>
 <th class="text--gray">Critical</th>
 <th class="text--gray">Deceased</th>
 <th class="text--gray">Changes Today</th>
 <th class="text--gray">Percentage Death Change</th>
 <th class="text--gray">Tests</th>
 <th class="text--gray">Active</th>
 <th class="text--gray">Recovered</th>
 </tr>,
 <tr>
 <td class="text--gray">
           TOTAL
         </td>
 <td class="text--green" data-order="14168735">
           14,168,735
         </td>
 <td class="text--green" data-order="229387">
           229,387
         </td>
 <td class="text--green" data-order="1.65">
           1.65%
         </td>
 <td class="text--orange" data-order="59936">
           59,936
         </td>
 <td class="text--red" data-order="598274">
           598,274
         </td>
 <td class="text--red" data-order="5292">
           5,292
         </td>
 <td class="text--red" data-order="0.89">
           0.89%
         </td>
 <td class="text--amber" data-order="287716113">
           287,716,113
         </td>
 <td class="text--yellow" data-order="5192356">
           5,192,356
         </td>
 <td class="text--blue" data-order="8210408">
           8,210,408
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Hong Kong" data-status="unselected" data-type="country">★</span>


             Hong Kong

         </td>
 <td class="text--green" data-order="1714">
           1,714
         </td>
 <td class="text--green" data-order="58">
           58
         </td>
 <td class="text--green" data-order="3.5">
           3.5%
         </td>
 <td class="text--orange" data-order="8">
           8
         </td>
 <td class="text--red" data-order="11">
           11
         </td>
 <td class="text--red" data-order="1">
           1
         </td>
 <td class="text--red" data-order="10">
           10%
         </td>
 <td class="text--amber" data-order="442256">
           442,256
         </td>
 <td class="text--yellow" data-order="439">
           439
         </td>
 <td class="text--blue" data-order="1264">
           1,264
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Macao" data-status="unselected" data-type="country">★</span>


             Macao

         </td>
 <td class="text--green" data-order="46">
           46
         </td>
 <td class="text--green" data-order="0">
           0
         </td>
 <td class="text--green" data-order="0">
           0%
         </td>
 <td class="text--orange" data-order="-1">
           Unknown
         </td>
 <td class="text--red" data-order="-1">
           Unknown
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="4071">
           4,071
         </td>
 <td class="text--yellow" data-order="-1">
           Unknown
         </td>
 <td class="text--blue" data-order="45">
           45
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Afghanistan" data-status="unselected" data-type="country">★</span>


             Afghanistan

         </td>
 <td class="text--green" data-order="35229">
           35,229
         </td>
 <td class="text--green" data-order="159">
           159
         </td>
 <td class="text--green" data-order="0.45">
           0.45%
         </td>
 <td class="text--orange" data-order="31">
           31
         </td>
 <td class="text--red" data-order="1147">
           1,147
         </td>
 <td class="text--red" data-order="34">
           34
         </td>
 <td class="text--red" data-order="3.05">
           3.05%
         </td>
 <td class="text--amber" data-order="82924">
           82,924
         </td>
 <td class="text--yellow" data-order="10931">
           10,931
         </td>
 <td class="text--blue" data-order="23151">
           23,151
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Albania" data-status="unselected" data-type="country">★</span>


             Albania

         </td>
 <td class="text--green" data-order="3906">
           3,906
         </td>
 <td class="text--green" data-order="55">
           55
         </td>
 <td class="text--green" data-order="1.43">
           1.43%
         </td>
 <td class="text--orange" data-order="9">
           9
         </td>
 <td class="text--red" data-order="107">
           107
         </td>
 <td class="text--red" data-order="3">
           3
         </td>
 <td class="text--red" data-order="2.88">
           2.88%
         </td>
 <td class="text--amber" data-order="30551">
           30,551
         </td>
 <td class="text--yellow" data-order="1585">
           1,585
         </td>
 <td class="text--blue" data-order="2214">
           2,214
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Algeria" data-status="unselected" data-type="country">★</span>


             Algeria

         </td>
 <td class="text--green" data-order="21948">
           21,948
         </td>
 <td class="text--green" data-order="593">
           593
         </td>
 <td class="text--green" data-order="2.78">
           2.78%
         </td>
 <td class="text--orange" data-order="61">
           61
         </td>
 <td class="text--red" data-order="1057">
           1,057
         </td>
 <td class="text--red" data-order="5">
           5
         </td>
 <td class="text--red" data-order="0.48">
           0.48%
         </td>
 <td class="text--amber" data-order="-1">
           Unknown
         </td>
 <td class="text--yellow" data-order="-1">
           Unknown
         </td>
 <td class="text--blue" data-order="15430">
           15,430
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Andorra" data-status="unselected" data-type="country">★</span>


             Andorra

         </td>
 <td class="text--green" data-order="880">
           880
         </td>
 <td class="text--green" data-order="3">
           3
         </td>
 <td class="text--green" data-order="0.34">
           0.34%
         </td>
 <td class="text--orange" data-order="-1">
           Unknown
         </td>
 <td class="text--red" data-order="52">
           52
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="3750">
           3,750
         </td>
 <td class="text--yellow" data-order="25">
           25
         </td>
 <td class="text--blue" data-order="803">
           803
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Angola" data-status="unselected" data-type="country">★</span>


             Angola

         </td>
 <td class="text--green" data-order="638">
           638
         </td>
 <td class="text--green" data-order="31">
           31
         </td>
 <td class="text--green" data-order="5.11">
           5.11%
         </td>
 <td class="text--orange" data-order="6">
           6
         </td>
 <td class="text--red" data-order="29">
           29
         </td>
 <td class="text--red" data-order="1">
           1
         </td>
 <td class="text--red" data-order="3.57">
           3.57%
         </td>
 <td class="text--amber" data-order="10000">
           10,000
         </td>
 <td class="text--yellow" data-order="410">
           410
         </td>
 <td class="text--blue" data-order="199">
           199
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Antigua and Barbuda" data-status="unselected" data-type="country">★</span>


             Antigua and Barbuda

         </td>
 <td class="text--green" data-order="74">
           74
         </td>
 <td class="text--green" data-order="0">
           0
         </td>
 <td class="text--green" data-order="0">
           0%
         </td>
 <td class="text--orange" data-order="1">
           1
         </td>
 <td class="text--red" data-order="3">
           3
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="901">
           901
         </td>
 <td class="text--yellow" data-order="14">
           14
         </td>
 <td class="text--blue" data-order="57">
           57
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Argentina" data-status="unselected" data-type="country">★</span>


             Argentina

         </td>
 <td class="text--green" data-order="119301">
           119,301
         </td>
 <td class="text--green" data-order="4518">
           4,518
         </td>
 <td class="text--green" data-order="3.94">
           3.94%
         </td>
 <td class="text--orange" data-order="752">
           752
         </td>
 <td class="text--red" data-order="2178">
           2,178
         </td>
 <td class="text--red" data-order="66">
           66
         </td>
 <td class="text--red" data-order="3.13">
           3.13%
         </td>
 <td class="text--amber" data-order="519281">
           519,281
         </td>
 <td class="text--yellow" data-order="67343">
           67,343
         </td>
 <td class="text--blue" data-order="49780">
           49,780
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Armenia" data-status="unselected" data-type="country">★</span>


             Armenia

         </td>
 <td class="text--green" data-order="34001">
           34,001
         </td>
 <td class="text--green" data-order="442">
           442
         </td>
 <td class="text--green" data-order="1.32">
           1.32%
         </td>
 <td class="text--orange" data-order="10">
           10
         </td>
 <td class="text--red" data-order="620">
           620
         </td>
 <td class="text--red" data-order="13">
           13
         </td>
 <td class="text--red" data-order="2.14">
           2.14%
         </td>
 <td class="text--amber" data-order="143114">
           143,114
         </td>
 <td class="text--yellow" data-order="10889">
           10,889
         </td>
 <td class="text--blue" data-order="22492">
           22,492
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Austria" data-status="unselected" data-type="country">★</span>


             Austria

         </td>
 <td class="text--green" data-order="19439">
           19,439
         </td>
 <td class="text--green" data-order="169">
           169
         </td>
 <td class="text--green" data-order="0.88">
           0.88%
         </td>
 <td class="text--orange" data-order="11">
           11
         </td>
 <td class="text--red" data-order="711">
           711
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="734413">
           734,413
         </td>
 <td class="text--yellow" data-order="1393">
           1,393
         </td>
 <td class="text--blue" data-order="17335">
           17,335
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Azerbaijan" data-status="unselected" data-type="country">★</span>


             Azerbaijan

         </td>
 <td class="text--green" data-order="26636">
           26,636
         </td>
 <td class="text--green" data-order="471">
           471
         </td>
 <td class="text--green" data-order="1.8">
           1.8%
         </td>
 <td class="text--orange" data-order="66">
           66
         </td>
 <td class="text--red" data-order="341">
           341
         </td>
 <td class="text--red" data-order="7">
           7
         </td>
 <td class="text--red" data-order="2.1">
           2.1%
         </td>
 <td class="text--amber" data-order="601500">
           601,500
         </td>
 <td class="text--yellow" data-order="8490">
           8,490
         </td>
 <td class="text--blue" data-order="17805">
           17,805
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="The Bahamas" data-status="unselected" data-type="country">★</span>


             The Bahamas

         </td>
 <td class="text--green" data-order="129">
           129
         </td>
 <td class="text--green" data-order="5">
           5
         </td>
 <td class="text--green" data-order="4.03">
           4.03%
         </td>
 <td class="text--orange" data-order="1">
           1
         </td>
 <td class="text--red" data-order="11">
           11
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="2570">
           2,570
         </td>
 <td class="text--yellow" data-order="27">
           27
         </td>
 <td class="text--blue" data-order="91">
           91
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Bahrain" data-status="unselected" data-type="country">★</span>


             Bahrain

         </td>
 <td class="text--green" data-order="35473">
           35,473
         </td>
 <td class="text--green" data-order="389">
           389
         </td>
 <td class="text--green" data-order="1.11">
           1.11%
         </td>
 <td class="text--orange" data-order="47">
           47
         </td>
 <td class="text--red" data-order="124">
           124
         </td>
 <td class="text--red" data-order="3">
           3
         </td>
 <td class="text--red" data-order="2.48">
           2.48%
         </td>
 <td class="text--amber" data-order="710686">
           710,686
         </td>
 <td class="text--yellow" data-order="4161">
           4,161
         </td>
 <td class="text--blue" data-order="31188">
           31,188
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Bangladesh" data-status="unselected" data-type="country">★</span>


             Bangladesh

         </td>
 <td class="text--green" data-order="199357">
           199,357
         </td>
 <td class="text--green" data-order="3034">
           3,034
         </td>
 <td class="text--green" data-order="1.55">
           1.55%
         </td>
 <td class="text--orange" data-order="1">
           1
         </td>
 <td class="text--red" data-order="2547">
           2,547
         </td>
 <td class="text--red" data-order="51">
           51
         </td>
 <td class="text--red" data-order="2.04">
           2.04%
         </td>
 <td class="text--amber" data-order="1006751">
           1,006,751
         </td>
 <td class="text--yellow" data-order="88085">
           88,085
         </td>
 <td class="text--blue" data-order="108725">
           108,725
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Barbados" data-status="unselected" data-type="country">★</span>


             Barbados

         </td>
 <td class="text--green" data-order="104">
           104
         </td>
 <td class="text--green" data-order="0">
           0
         </td>
 <td class="text--green" data-order="0">
           0%
         </td>
 <td class="text--orange" data-order="-1">
           Unknown
         </td>
 <td class="text--red" data-order="7">
           7
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="9270">
           9,270
         </td>
 <td class="text--yellow" data-order="6">
           6
         </td>
 <td class="text--blue" data-order="91">
           91
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Belarus" data-status="unselected" data-type="country">★</span>


             Belarus

         </td>
 <td class="text--green" data-order="65782">
           65,782
         </td>
 <td class="text--green" data-order="159">
           159
         </td>
 <td class="text--green" data-order="0.24">
           0.24%
         </td>
 <td class="text--orange" data-order="89">
           89
         </td>
 <td class="text--red" data-order="491">
           491
         </td>
 <td class="text--red" data-order="6">
           6
         </td>
 <td class="text--red" data-order="1.24">
           1.24%
         </td>
 <td class="text--amber" data-order="1162280">
           1,162,280
         </td>
 <td class="text--yellow" data-order="7921">
           7,921
         </td>
 <td class="text--blue" data-order="57370">
           57,370
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Belgium" data-status="unselected" data-type="country">★</span>


             Belgium

         </td>
 <td class="text--green" data-order="63238">
           63,238
         </td>
 <td class="text--green" data-order="199">
           199
         </td>
 <td class="text--green" data-order="0.32">
           0.32%
         </td>
 <td class="text--orange" data-order="28">
           28
         </td>
 <td class="text--red" data-order="9795">
           9,795
         </td>
 <td class="text--red" data-order="3">
           3
         </td>
 <td class="text--red" data-order="0.03">
           0.03%
         </td>
 <td class="text--amber" data-order="1429053">
           1,429,053
         </td>
 <td class="text--yellow" data-order="36174">
           36,174
         </td>
 <td class="text--blue" data-order="17269">
           17,269
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Belize" data-status="unselected" data-type="country">★</span>


             Belize

         </td>
 <td class="text--green" data-order="40">
           40
         </td>
 <td class="text--green" data-order="0">
           0
         </td>
 <td class="text--green" data-order="0">
           0%
         </td>
 <td class="text--orange" data-order="-1">
           Unknown
         </td>
 <td class="text--red" data-order="2">
           2
         </td>
 <td class="text--red" data-order="0">
           0
         </td>
 <td class="text--red" data-order="0">
           0%
         </td>
 <td class="text--amber" data-order="2786">
           2,786
         </td>
 <td class="text--yellow" data-order="16">
           16
         </td>
 <td class="text--blue" data-order="22">
           22
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Benin" data-status="unselected" data-type="country">★</span>


             Benin

         </td>
 <td class="text--green" data-order="1602">
           1,602
         </td>
 <td class="text--green" data-order="139">
           139
         </td>
 <td class="text--green" data-order="9.5">
           9.5%
         </td>
 <td class="text--orange" data-order="1">
           1
         </td>
 <td class="text--red" data-order="31">
           31
         </td>
 <td class="text--red" data-order="3">
           3
         </td>
 <td class="text--red" data-order="10.71">
           10.71%
         </td>
 <td class="text--amber" data-order="72832">
           72,832
         </td>
 <td class="text--yellow" data-order="789">
           789
         </td>
 <td class="text--blue" data-order="782">
           782
         </td>
 </tr>,
 <tr>
 <td class="text--gray">
 <span class="save-button" data-name="Bhutan" data-status="unselected" data-type="country">★</span>


             Bhutan

         </td>
 <td class="text--green" data-order="86">
           86
         </td>
 <td class="text--green" data-order="2">
           2
         </td>
 <td class="text--green" data-order="2.38">
           2.38%

In [7]:
tableCols = tableRows[1].findAll('td')
tableCol = tableCols[0]
tableCol

<td class="text--gray">
          TOTAL
        </td>

In [8]:
tableCol.text

'\r\n          TOTAL\r\n        '

In [9]:
tableCol.text.strip()

'TOTAL'

In [10]:
tableCol2 = tableRows[1].findAll('td')[2].text.strip()
tableCol2

'229,387'

In [26]:
for row in tableRows[1:]:
    if 'United States' == row.find('td').text[2:].strip():
        columns = row.findAll('td')
        print(f'Confirmed: {columns[1].text.strip()}')
        print(f'Changes: {columns[2].text.strip()}')
        print(f'Critical: {columns[3].text.strip()}')

Confirmed: 3,762,881
Changes: 67,856
Critical: 1.84%

In [21]:
for row in tableRows[1:]:
    print(row.find('td').text[2:].strip())

TOTAL
Hong Kong
Macao
Afghanistan
Albania
Algeria
Andorra
Angola
Antigua and Barbuda
Argentina
Armenia
Austria
Azerbaijan
The Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brunei
Bulgaria
Burkina Faso
Myanmar
Burundi
Cape Verde
Cambodia
Cameroon
Central African Republic
Chad
Comoros
Congo
DR Congo
Costa Rica
Ivory Coast
Croatia
Cuba
Cyprus
Czechia
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
The Gambia
Georgia
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Vatican City
Honduras
Hungary
Iceland
Indonesia
Iran
Iraq
Ireland
Israel
Jamaica
Jordan
Kazakhstan
Kenya
South Korea
Kosovo
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Mauritania
Mauritius
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Namibia
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Panama
Papua New Guinea
Paraguay
Philippines
Poland
Portugal
Qatar
Romania
Rwanda
Saint Kitts and Nevis
Saint Lucia
Saint Vincent and the Grenadines
San Marino
SÃ£o TomÃ© and PrÃ­ncipe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Somalia
South Africa
South Sudan
Sri Lanka
Sudan
Suriname
Switzerland
Syria
Taiwan
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Trinidad and Tobago
Tunisia
Turkey
Uganda
United Arab Emirates
Uruguay
Uzbekistan
Venezuela
Vietnam
Palestine
Western Sahara
Yemen
Zambia
Zimbabwe
United States
Brazil
India
Russia
Peru
Chile
Mexico
Spain
United Kingdom
Pakistan
Italy
Germany
Colombia
Canada
Sweden
Ukraine
Japan
Australia
French Guiana
Mayotte
Reunion
Channel Islands
Isle of Man
Martinique
Cayman Islands
Guadeloupe
Faroe Islands
Gibraltar
Bermuda
Aruba
Sint Maarten
Turks and Caicos Islands
French Polynesia
Saint Martin
Curacao
New Caledonia
Falkland Islands
Greenland
Montserrat
Caribbean Netherlands
British Virgin Islands
Saint Barthelemy
Saint Pierre and Miquelon
Anguilla
China